# Generated by Django 4.2 on 2025-10-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winnieclubapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='min_stock_level',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
