# Generated by Django 4.2 on 2025-09-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winnieclubapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
