# Generated by Django 4.2 on 2025-09-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winnieclubapp', '0003_alter_stockitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='worker_photos/')),
            ],
        ),
    ]
